- name: Install application resources
  hosts: masters
  become: true
  tasks:
    - name: Add ArgoCd repository
      kubernetes.core.helm_repository:
        name: argocd
        repo_url: https://prometheus-community.github.io/helm-charts
        state: present
    - name: Add Longhorn repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present
    - name: Install Longhorn through helm
      kubernetes.core.helm:
        atomic: true
        name: longhorn
        namespace: longhorn-system
        chart_version: 1.7.2
        update_repo_cache: true
        create_namespace: true
        chart_ref: longhorn/longhorn
        release_state: present
        wait: true
    - name: Install Prometheus stack through helm
      kubernetes.core.helm:
        atomic: true
        name: kube-prometheus-stack
        namespace: monitoring
        chart_version: 62.3.1
        update_repo_cache: true
        create_namespace: true
        chart_ref: prometheus-community/kube-prometheus-stack
        release_state: present
        wait: true
